# 全局配置
global:
  scrape_interval: 15s # 每15秒从目标拉取一次监控指标
  evaluation_interval: 15s # 每15秒评估一次告警规则

# 告警规则管理 (Alerting)
# 暂时可以不配置，但保留结构
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# 监控指标拉取配置
scrape_configs:
  # 第一个job: 监控Prometheus自身
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:18080']  # 改成你的 Spring Boot 服务地址
  - job_name: 'nacos-server'
    metrics_path: '/nacos/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8848']  # 改成你运行 Nacos 的地址
  - job_name: 'pinyougou-services'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - 'HOST.DOCKER.INTERNAL:18080'  # pinyougou-gateway
          - 'HOST.DOCKER.INTERNAL:18081'  # pinyougou-user-service
          - 'HOST.DOCKER.INTERNAL:18082'  # pinyougou-product-service