# 全局配置
global:
  scrape_interval: 15s # 每15秒从目标拉取一次监控指标
  evaluation_interval: 15s # 每15秒评估一次告警规则

# 告警规则管理 (Alerting)
# 暂时可以不配置，但保留结构
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# 监控指标拉取配置
scrape_configs:
  # 第一个job: 监控Prometheus自身
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'nacos'
    metrics_path: /nacos/metrics
    static_configs:
      - targets: ['nacos:8848']
  - job_name: 'pinyougou-services'
    # 使用Nacos作为服务发现
    nacos_sd_configs:
      - server: 'host.docker.internal:8848' # **关键**: 从容器内访问宿主机的Nacos
    relabel_configs:
      # 只保留暴露了/actuator/prometheus接口的服务
      - source_labels: [__meta_nacos_service_metadata_actuator_prometheus_exist]
        action: keep
        regex: true
      # 从Nacos元数据中提取服务名作为实例标识
      - source_labels: [__meta_nacos_service_name, __meta_nacos_instance_ip, __meta_nacos_instance_port]
        separator: ':'
        target_label: instance